### ISSUE TITLE
Multiqc kraken module fails when sample has zero unclassified reads.

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/routine-sequence-qc#62]
When a sample has zero unclassified reads, we get a `ZeroDivisionError` in the kraken module of MultiQC:

```
[ERROR  ]         multiqc : Oops! The 'kraken' MultiQC module broke... 
    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
    If possible, please include a log file that triggers the error - the last file found was:
      ./Undetermined_Species_multiqc_bracken.txt
  ============================================================
Module kraken raised an exception: Traceback (most recent call last):
    File "/path/to/conda_envs/routine-qc-a7f32b1edccdcdea098b345cb8f76335/lib/python3.8/site-packages/multiqc/multiqc.py", line 569, in run
      output = mod()
    File "/path/to/conda_envs/routine-qc-a7f32b1edccdcdea098b345cb8f76335/lib/python3.8/site-packages/multiqc/modules/kraken/kraken.py", line 60, in __init__
      self.sum_sample_counts()
    File "/path/to/conda_envs/routine-qc-a7f32b1edccdcdea098b345cb8f76335/lib/python3.8/site-packages/multiqc/modules/kraken/kraken.py", line 134, in sum_sample_counts
      self.kraken_sample_total_readcounts[s_name] = round(float(row['counts_rooted']) / (row['percent'] / 100.0))
  ZeroDivisionError: float division by zero
```

**Comment by dfornika** [comment]
This issue has been fixed in MultiQC v1.11:

https://github.com/ewels/MultiQC/issues/1440

...so updating the version of MultiQC used in this pipeline should resolve this issue.

Fixed in this commit: https://github.com/ewels/MultiQC/commit/3cb88c4d82b0d0e5337d9e105db1e093644bde5f
